name: deploy-blazorui-prd
env:
  PUBLISH_DIR: identityguard.blazor.ui/bin/Release/net5.0/publish/wwwroot

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["continuous-integration"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Tests
      run: dotnet test

    - name: Publish app
      run: dotnet publish -c Release

    - name: Set base href in index
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /
      
    - name: Publish to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.PUBLISH_DIR }}
        publish_branch: release/blazor-ui