name: deploy-prd
env:
  UI_PUBLISH_DIR: src/IdentityGuard.Blazor.Ui/bin/Release/net5.0/publish/wwwroot
  API_PUBLISH_DIR: src/IdentityGuard.Api/bin/Release/net5.0/publish
  APP_INSIGHTS_ID: 05f8076a-1c7a-43b0-a86b-dd91c2067c9e
  UI_CLIENT_ID: c8e4d4d8-64ce-4515-b60b-985fd7eb6a3f
  API_FUNCTION_NAME: idguard-api-prd
  API_URL: https://idguard-api-prd.azurewebsites.net
  API_SCOPE: api://idguard-api-prd/user_impersonation
  UI_BLOB_NAME: idguardwebprd
  WORKER_FUNCTION_NAME: idguard-worker-prd
  WORKER_PUBLISH_DIR: src/IdentityGuard.Worker/bin/Release/net5.0/publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["continuous-integration"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2

    - name: Publish app
      run: dotnet publish -c Release

    - name: Set Azure AD Client Id
      uses: benday-inc/set-property-value-in-appsettings@v1.1
      with:
        pathtosettingsfile: '${{ env.UI_PUBLISH_DIR }}/appsettings.json'
        keyname1: 'AzureAd'
        keyname2: 'ClientId'
        valuetoset: '${{ env.UI_CLIENT_ID }}'

    - name: Set Application Insights Instrumentation Key
      uses: benday-inc/set-property-value-in-appsettings@v1.1
      with:
        pathtosettingsfile: '${{ env.UI_PUBLISH_DIR }}/appsettings.json'
        keyname1: 'ApplicationInsights'
        keyname2: 'InstrumentationKey'
        valuetoset: '${{ env.APP_INSIGHTS_ID }}'

    - name: Set API Url
      uses: benday-inc/set-property-value-in-appsettings@v1.1
      with:
        pathtosettingsfile: '${{ env.UI_PUBLISH_DIR }}/appsettings.json'
        keyname1: 'Api'
        keyname2: 'Url'
        valuetoset: '${{ env.API_URL }}'

    - name: Set API Scope
      uses: benday-inc/set-property-value-in-appsettings@v1.1
      with:
        pathtosettingsfile: '${{ env.UI_PUBLISH_DIR }}/appsettings.json'
        keyname1: 'Api'
        keyname2: 'Scope'
        valuetoset: '${{ env.API_SCOPE }}'

    - name: Service Principal Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload Static Site
      uses: azure/CLI@v1
      with:
        inlineScript: az storage blob upload-batch --account-name '${{ env.UI_BLOB_NAME }}' --auth-mode key -d '$web' -s ${{ env.UI_PUBLISH_DIR }}

    - name: Deploy API Azure Function
      uses: Azure/functions-action@v1
      id: api
      with:
        app-name: ${{ env.API_FUNCTION_NAME }}
        package: ${{ env.API_PUBLISH_DIR }}

    - name: Deploy Worker Azure Function
      uses: Azure/functions-action@v1
      id: worker
      with:
        app-name: ${{ env.WORKER_FUNCTION_NAME }}
        package: ${{ env.WORKER_PUBLISH_DIR }}

    - name: Service Principal Logout
      run: az logout