name: deploy-prd
env:
  PUBLISH_DIR: identityguard.blazor.ui/bin/Release/net5.0/publish/wwwroot

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["continuous-integration"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Tests
      run: dotnet test

    - name: Publish app
      run: dotnet publish -c Release

    - name: Service Principal Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload Static Site
      uses: azure/CLI@v1
      with:
        inlineScript: az storage blob upload-batch --account-name idguardwebprd --auth-mode key -d '$web' -s ${{ env.PUBLISH_DIR }}